version: '3.7'
services:
  web:
    build: ./django_data
    command: gunicorn django_project.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/code
      - static_volume:/code/django_data/staticfiles
      - media_volume:/code/django_data/mediafiles
    expose:
      - 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:11
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
  static_volume:
  media_volume:
