# Generated by Django 3.1.1 on 2020-11-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201102_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='richie', max_length=200),
            preserve_default=False,
        ),
    ]
