# Generated by Django 3.1.1 on 2020-11-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(default='www.google.com'),
            preserve_default=False,
        ),
    ]
