# Generated by Django 3.1.1 on 2021-01-04 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_richtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richtext',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richtexts', to='blog.article'),
        ),
    ]
