# Generated by Django 3.1.1 on 2021-01-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210104_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='richtext',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='richtext',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
